// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueuedTurnStatus } from "./QueuedTurnStatus";
import type { TurnStartParams } from "./TurnStartParams";

export type QueuedTurn = { id: string, turnStartParams: TurnStartParams, status: QueuedTurnStatus, };
